#!/usr/bin/env python3
"""Build normalized Indian name lists from raw source data."""
from __future__ import annotations

import argparse
import csv
import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data" / "indian_names"
OUTPUT_MODULE = ROOT / "backend" / "generated_indian_names.py"

SOURCE_FILES = {
    "INDIAN_FIRST_NAMES": DATA_DIR / "wikidata_indian_given_names.csv",
    "INDIAN_SURNAMES": DATA_DIR / "wikidata_indian_family_names.csv",
}


def normalize_name(raw: str) -> str | None:
    cleaned = re.sub(r"\s+", " ", raw.strip())
    cleaned = re.sub(r"[^A-Za-z'\-\s]", "", cleaned)
    cleaned = cleaned.strip()
    if not cleaned:
        return None
    return cleaned.title()


def load_names(path: Path) -> set[str]:
    if not path.exists():
        raise FileNotFoundError(f"Missing source file: {path}")
    names: set[str] = set()
    with path.open("r", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            return names
        if "name" not in reader.fieldnames:
            raise ValueError(f"Expected 'name' column in {path}")
        for row in reader:
            raw = row.get("name") or ""
            normalized = normalize_name(raw)
            if normalized:
                names.add(normalized)
    return names


def format_set(name: str, values: set[str]) -> str:
    lines = [f"{name} = {{"]
    for value in sorted(values):
        lines.append(f"    {value!r},")
    lines.append("}")
    return "\n".join(lines)


def build_module() -> str:
    first_names = load_names(SOURCE_FILES["INDIAN_FIRST_NAMES"])
    surnames = load_names(SOURCE_FILES["INDIAN_SURNAMES"])
    header = (
        "\"\"\"Generated Indian name lists.\n\n"
        "This file is auto-generated by scripts/build_indian_name_lists.py.\n"
        "Do not edit by hand.\n"
        "\"\"\""
    )
    content = [
        header,
        "",
        "from __future__ import annotations",
        "",
        format_set("INDIAN_FIRST_NAMES", first_names),
        "",
        format_set("INDIAN_SURNAMES", surnames),
        "",
    ]
    return "\n".join(content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated module is up to date without writing.",
    )
    args = parser.parse_args()

    generated = build_module()

    if args.check:
        if not OUTPUT_MODULE.exists():
            print("Generated module does not exist.")
            return 1
        current = OUTPUT_MODULE.read_text(encoding="utf-8")
        if current != generated:
            diff = "\n".join(
                difflib.unified_diff(
                    current.splitlines(),
                    generated.splitlines(),
                    fromfile=str(OUTPUT_MODULE),
                    tofile="generated",
                    lineterm="",
                )
            )
            print(diff)
            return 1
        print("Generated Indian name module is up to date.")
        return 0

    OUTPUT_MODULE.write_text(generated, encoding="utf-8")
    print(f"Wrote {OUTPUT_MODULE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
